# Generated by Django 4.2.4 on 2024-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('tipodocente', models.CharField(max_length=200)),
                ('password', models.CharField(default='password', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='none', max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField(max_length=200)),
                ('horaFin', models.TimeField(max_length=200)),
                ('modalidad', models.CharField(max_length=200)),
                ('plataforma', models.CharField(default='none', max_length=200)),
                ('link', models.CharField(default='none', max_length=200)),
                ('ambiente', models.CharField(default='none', max_length=200)),
                ('detalle', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
