# Generated by Django 4.2.4 on 2024-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(default='none', max_length=200)),
                ('tipodocente', models.CharField(default='none', max_length=200)),
                ('departamento', models.CharField(default='none', max_length=200)),
                ('materia', models.CharField(default='none', max_length=200)),
                ('dia', models.CharField(default='none', max_length=200)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField(max_length=200)),
                ('horaFin', models.TimeField(max_length=200)),
                ('modalidad', models.CharField(max_length=200)),
                ('plataforma', models.CharField(default='none', max_length=200)),
                ('link', models.CharField(default='none', max_length=200)),
                ('ambiente', models.CharField(default='none', max_length=200)),
                ('detalleambiente', models.CharField(default='none', max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('nombreestudiante', models.CharField(default='none', max_length=200)),
                ('carreraestudiante', models.CharField(default='none', max_length=200)),
                ('semestreestudiante', models.CharField(default='none', max_length=200)),
                ('atencion', models.CharField(default='none', max_length=200)),
                ('temaconsulta', models.CharField(default='none', max_length=200)),
                ('detalletemaconsulta', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
