# Generated by Django 4.2.4 on 2024-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0002_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='modalidad',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
