# Generated by Django 4.2.4 on 2024-07-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0004_marketing_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketing',
            new_name='ProgramarSesiones',
        ),
    ]
