# Generated by Django 4.2.4 on 2024-07-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0005_rename_marketing_programarsesiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='programarsesiones',
            name='correoestudiante',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
