# Generated by Django 4.2.4 on 2024-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0008_programarsesiones_confirmacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
            ],
        ),
    ]
