# Generated by Django 4.2.4 on 2024-08-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_imt', '0009_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(default='none', max_length=200)),
                ('tipodocente', models.CharField(default='none', max_length=200)),
                ('departamento', models.CharField(default='none', max_length=200)),
                ('materia', models.CharField(default='none', max_length=200)),
                ('dia', models.CharField(default='none', max_length=200)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField(max_length=200)),
                ('horaFin', models.TimeField(max_length=200)),
                ('modalidad', models.CharField(default='none', max_length=200)),
                ('plataforma', models.CharField(default='none', max_length=200)),
                ('link', models.CharField(default='none', max_length=200)),
                ('ambiente', models.CharField(default='none', max_length=200)),
                ('detalleambiente', models.CharField(default='none', max_length=500)),
                ('estado', models.CharField(max_length=200)),
                ('nombreestudiante', models.CharField(default='none', max_length=200)),
                ('carreraestudiante', models.CharField(default='none', max_length=200)),
                ('semestreestudiante', models.CharField(default='none', max_length=200)),
                ('correoestudiante', models.CharField(default='none', max_length=200)),
                ('atencion', models.CharField(default='none', max_length=200)),
                ('cantidad', models.CharField(default='none', max_length=200)),
                ('temaconsulta', models.CharField(default='none', max_length=200)),
                ('detalletemaconsulta', models.CharField(default='none', max_length=400)),
                ('confirmacion', models.CharField(default='none', max_length=200)),
                ('comentariosdocentesesion', models.CharField(default='none', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='atencion',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='carreraestudiante',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='comentariosdocentesesion',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='confirmacion',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='correoestudiante',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='detalleambiente',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='detalletemaconsulta',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='link',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='nombreestudiante',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='semestreestudiante',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='temaconsulta',
        ),
    ]
